//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribtion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscribtion()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int subscribtionId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int price { get; set; }
        public string periodicity { get; set; }
        public int editionId { get; set; }
    
        public virtual Edition Edition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
